name       : latencytop
version    : 0.5
release    : 2
source     :
    - http://ftp.de.debian.org/debian/pool/main/l/latencytop/latencytop_0.5.orig.tar.gz : 9e7f72fbea7bd918e71212a1eabaad8488d2c602205d2e3c95d62cd57e9203ef
license    : GPL-2.0
summary    : LatencyTOP
component  : system.utils
description: |
    LatencyTOP is a Linux application for identifying operating system latency within the kernel and find out the operations/actions which cause the latency. LatencyTOP is a tool for software developers to visualize system latencies. Based on these observations, the source code of the application or kernel can be modified to reduce latency. It was released by Intel in 2008 under the GPLv2 license. It works for Intel, AMD and ARM processors.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(ncursesw)
build      : |
    %make
install    : |
    install -D latencytop.8 %installroot%/usr/share/man/man8/latencytop.8
    install -D user_process.png %installroot%/usr/share/latencytop/user_process.png
    install -D latencytop.trans %installroot%/usr/share/latencytop/latencytop.trans
    install -D kernel_thread.png %installroot%/usr/share/latencytop/kernel_thread.png
    install -D global.png %installroot%/usr/share/latencytop/global.png
    install -D latencytop %installroot%/usr/bin/latencytop

